### PR TITLE
 [CSE 276F Submission] - PullCubeWithHockeyStick-v1

### PR DESCRIPTION
**Pull request by szczekulskij**
- A simple task where the robot needs to pick up a hockey stick and use it to pull the cube towards the pre-specified target.
- Successful ppo run (can be further hyper-tuned for quicker convergence): `python examples/baselines/ppo/ppo.py --env_id="PullCubeWithHockeyStick-v1"  --num_envs=2048 --eval_freq=10 --seed=42 --total_timesteps=40_000_000 --num-steps=100 --num_eval_steps=100`
- This PR is part of the project 2 of CSE 276F, which includes two co-authors: Jan Szczekulski & Hongseok Oh
- I'm sorry for the messy commit history, I had to write code on MacOs metal and run in jupyter notebook.
- Despite spending 3hrs on it, I'm unable to run rendering with `shader_dir="rt"`. I've tried changing ppo's `gym.make()` code, but nothing seemed to work. Could I please request help with this? I'm attaching link to weights of trained model here: https://drive.google.com/file/d/19QBOz7m6dp5iMeW3SFfktGNk3zNCE1Hc/view?usp=sharing

### CODE REVIEW

**Comment by szczekulskij** [comment]
@StoneT2000, could I request a review on this PR please ?
Thank you !

**Comment by StoneT2000** [comment]
Thank you for your contribution. I think the task is a bit too easy relative to the PullCube task since the hockey stick is not necessarily realistically (you can pull it back). I recommend modifying the task so that the hockey stick is absolutely necessary to solve the task. 

Some options
- Pull three objects back (within the 50 step time horizon you will then need the stick to pull them back in time)
- Pull object from very far away and back.

Also hockey stick is a bit thin, which could make the task harder I guess. I'd recommend making it slightly more thick.

**Comment by szczekulskij** [comment]
Thanks for feedback. Quick question - is this env good enough to get full marks on project2? I'll work on making it better regardless, but I already generated report & analysis based on this environment for project 2, and would be shame to waste that effort

**Comment by StoneT2000** [comment]
for the project itself any env is basically fine as long as its your own work

**Review by StoneT2000 — CHANGES_REQUESTED** [review]
just making the review a request changes review. Re-request a review when this PR is ready

**Pull request closed without merging**
